### PR TITLE
Update to Dash

### PR DESCRIPTION
**Pull request by schinzelh**
Hi @chaeplin,

hope you are doing fine. This updates your repo to python-x11-hash-1.4.

Question: Any chance to transfer the ownership of 'chaeplin/xcoin-hash' repo to me (i assume you don't want to maintain it anymore)?

Thanks,
Holger

### CODE REVIEW

**Comment by chaeplin** [comment]
@schinzelh HI ^^
Transfer has error. I will try again.

**Comment by schinzelh** [comment]
@chaeplin Much appreciated - please transfer to "dashdot" organization. Thanks!

**Comment by chaeplin** [comment]
@schinzelh dashdot!! done:)

**Comment by schinzelh** [comment]
@chaeplin perfect, many thanks! :)

**Pull request merged**
